title: Ethical HACCers
description: Ethical HACCers
google_analytics:
show_downloads: true
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: https://github.com/ethical-haccers
gems:
  - jekyll-mentions
